#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative './lexer'

class HCLParser < Racc::Parser

module_eval(<<'...end parse.y/module_eval...', 'parse.y', 123)
  #//
  #//       HCL is unclear on what one should do when duplicate
  #//       keys are encountered.
  #//
  #//       from decoder.go: if we're at the root or we're directly within
  #//                        a list, decode  to hashes, otherwise lists
  #//
  #//       from object.go:  there is a flattened list structure
  #//
  def flatten_objectlist(list)
    (list || {}).each_with_object({}) do |a, h|
      h[a.first] =
        case a.last
        when Hash
          deep_merge(h[a.first] || {}, a.last)
        else
          h[a.first] = a.last
        end
    end
  end


  def on_error(error_token_id, error_value, value_stack)
    error_message = value_stack.to_s.split(',').last.gsub(']', '')
    header = "Parse error at #{error_message} #{error_value} (invalid token: #{error_value})"
    raise Racc::ParseError, header
  end


  def parse(input)
    @lexer = HCLLexer.new.lex(input)
    do_parse
    return @result
  end


  def next_token
    @lexer.shift
  end

  def deep_merge(hash1, hash2)
    hash2.keys.each do |key|
      value1 = hash1[key]
      value2 = hash2[key]

      if value1.is_a?(Hash) && value2.is_a?(Hash)
        hash1[key] = deep_merge(value1, value2)
      else
        hash1[key] = value2
      end
    end

    hash1
  end
...end parse.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    22,    28,    27,    10,    28,    27,     5,    23,     6,    14,
    35,    26,    14,    12,    26,    32,    28,    27,    40,     5,
   -10,     6,    35,     5,    14,     6,    26,    39,    30,     5,
   -11,     6,    13,    17,    38,    18,    19,    14,    20 ]

racc_action_check = [
    13,    13,    13,     1,    26,    26,     0,    13,     0,    13,
    26,    13,    26,     4,    26,    26,    40,    40,    31,     3,
     5,     3,    40,    14,    40,    14,    40,    31,    14,    29,
     6,    29,     7,     9,    29,     9,    10,     9,    11 ]

racc_action_pointer = [
    -1,     3,   nil,    12,     8,    12,    22,    24,   nil,    26,
    36,    33,   nil,    -2,    16,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     1,   nil,   nil,    22,
   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    13,   nil ]

racc_action_default = [
    -2,   -33,    -1,    -3,    -5,   -20,   -21,   -33,   -17,   -33,
   -33,    -7,    -4,   -33,   -33,   -18,   -19,   -20,   -21,    42,
    -6,   -12,   -13,   -14,   -15,   -16,   -33,   -31,   -32,   -33,
    -9,   -33,   -23,   -24,   -27,   -28,   -29,   -30,    -8,   -22,
   -26,   -25 ]

racc_goto_table = [
    11,     3,    33,    15,     1,     2,    21,    24,    25,    16,
    31,   nil,   nil,   nil,   nil,    29,    41,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    11 ]

racc_goto_check = [
     4,     3,    12,     5,     1,     2,     7,     5,     8,     9,
    11,   nil,   nil,   nil,   nil,     3,    12,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     4 ]

racc_goto_pointer = [
   nil,     4,     5,     1,    -3,    -6,   nil,    -7,    -5,     0,
   nil,   -16,   -24 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     4,    37,     7,    34,    36,     8,
     9,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 19, :_reduce_1,
  0, 20, :_reduce_2,
  1, 20, :_reduce_none,
  2, 21, :_reduce_4,
  1, 21, :_reduce_5,
  3, 21, :_reduce_6,
  2, 21, :_reduce_7,
  3, 23, :_reduce_8,
  2, 23, :_reduce_9,
  1, 24, :_reduce_10,
  1, 24, :_reduce_11,
  3, 22, :_reduce_12,
  3, 22, :_reduce_13,
  3, 22, :_reduce_14,
  3, 22, :_reduce_15,
  3, 22, :_reduce_16,
  1, 22, :_reduce_17,
  2, 27, :_reduce_18,
  2, 27, :_reduce_19,
  1, 28, :_reduce_20,
  1, 28, :_reduce_21,
  3, 26, :_reduce_22,
  2, 26, :_reduce_23,
  1, 29, :_reduce_24,
  3, 29, :_reduce_25,
  2, 29, :_reduce_26,
  1, 30, :_reduce_27,
  1, 30, :_reduce_28,
  1, 30, :_reduce_29,
  1, 30, :_reduce_30,
  1, 25, :_reduce_31,
  1, 25, :_reduce_32 ]

racc_reduce_n = 33

racc_shift_n = 42

racc_token_table = {
  false => 0,
  :error => 1,
  :BOOL => 2,
  :FLOAT => 3,
  :NUMBER => 4,
  :COMMA => 5,
  :COMMAEND => 6,
  :IDENTIFIER => 7,
  :EQUAL => 8,
  :STRING => 9,
  :MINUS => 10,
  :LEFTBRACE => 11,
  :RIGHTBRACE => 12,
  :LEFTBRACKET => 13,
  :RIGHTBRACKET => 14,
  :PERIOD => 15,
  :EPLUS => 16,
  :EMINUS => 17 }

racc_nt_base = 18

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "BOOL",
  "FLOAT",
  "NUMBER",
  "COMMA",
  "COMMAEND",
  "IDENTIFIER",
  "EQUAL",
  "STRING",
  "MINUS",
  "LEFTBRACE",
  "RIGHTBRACE",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "PERIOD",
  "EPLUS",
  "EMINUS",
  "$start",
  "target",
  "top",
  "objectlist",
  "objectitem",
  "object",
  "objectkey",
  "number",
  "list",
  "block",
  "block_id",
  "listitems",
  "listitem" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parse.y', 19)
  def _reduce_1(val, _values, result)
     @result = flatten_objectlist(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 22)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

# reduce 3 omitted

module_eval(<<'.,.,', 'parse.y', 29)
  def _reduce_4(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 31)
  def _reduce_5(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 33)
  def _reduce_6(val, _values, result)
     result = val[0] << val[1]  
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 35)
  def _reduce_7(val, _values, result)
     result = val[0] << val[1]  
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 40)
  def _reduce_8(val, _values, result)
     result = flatten_objectlist(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 42)
  def _reduce_9(val, _values, result)
     return 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 47)
  def _reduce_10(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 49)
  def _reduce_11(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 54)
  def _reduce_12(val, _values, result)
     result = val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 56)
  def _reduce_13(val, _values, result)
     result = val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 58)
  def _reduce_14(val, _values, result)
     result = val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 60)
  def _reduce_15(val, _values, result)
     result = val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 62)
  def _reduce_16(val, _values, result)
     result = val[0], val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 64)
  def _reduce_17(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 69)
  def _reduce_18(val, _values, result)
     result = val[0], val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 71)
  def _reduce_19(val, _values, result)
     result = val[0], {val[1][0] => val[1][1]} 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 76)
  def _reduce_20(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 78)
  def _reduce_21(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 83)
  def _reduce_22(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 85)
  def _reduce_23(val, _values, result)
     return 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 90)
  def _reduce_24(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 92)
  def _reduce_25(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 94)
  def _reduce_26(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 99)
  def _reduce_27(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 101)
  def _reduce_28(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 103)
  def _reduce_29(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 105)
  def _reduce_30(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 110)
  def _reduce_31(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 112)
  def _reduce_32(val, _values, result)
     result = val[0] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class HCLParser
